# This file should contain everything to configure the workflow on a global scale.

threads: 8
query_dir: "data/genomes/" # Location of query proteomes
tmp_dir: "data/mmseqs/search/tmp/" # Required for mmseqs search
search_dir: "data/mmseqs/search/" # Location of search output
og_seqs_dir: "data/OGs/" # Location of OG sequence files
msa_dir: "data/msa/" # Location of multi-sequence alignments
mmseqs_input_dir: "data/mmseqs/input/" # Location of pooled MSAs in a Stockholm file and MMSeqs DB (used to create profile)
profile_dir: "data/mmseqs/profile/" # Location of MMSeqs profile output
