
threads: 8

profile_match_ratio: 0.5
profile_extra: '' #extra commands supplied to msa2profile
suffix: ".faa"
aligner: "mafft"  # [clustalo, mafft]
hmmsearch_evalue: 10
mmseqs_search_commands: ""
# parameters for trimal

trimal:
  gapthreshold: 0.9
#  gappyout: "" #Use automated selection on "gappyout" mode. This method only uses information based on gaps' distribution. (see User Guide).
#  gapthreshold: 0.9    #1 - (fraction of sequences with a gap allowed). Range: [0 - 1]
#  cons: 60             #Minimum percentage of the positions in the original alignment to conserve. Range: [0 - 100]
#  simthreshold: <n>    #Minimum average similarity allowed. Range: [0 - 1]
#  conthreshold: <n>    #Minimum consistency value allowed.Range: [0 - 1]
